; generated by PrusaSlicer 2.6.1+linux-x64-GTK3 on 2023-10-08 at 23:45:29 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.70mm

;TYPE:Custom
; M190 R30 ; Because of probe temperature drift,
; M109 R30 ; Let the beds and hotend cool down before homing the axis

G28 ; home all axes
G1 Z5 F5000 ; lift nozzle
M190 S65 ; set bed temperature and wait for it to be reached
M109 S205 ; set hot end temp and wait for it

; Do a purge line to prime the extruder
G92 E0 ;Reset Extruder
G1 Z2.0 F3000 ;Move Z Axis up
G1 X20 Y5.1 Z0.28 F5000.0 ;Move to start position
G1 X200.0 Y5.1 Z0.28 F1500.0 E15 ;Draw the first line
G1 X200.0 Y5.4 Z0.28 F5000.0 ;Move to side a little
G1 X20 Y5.4 Z0.28 F1500.0 E30 ;Draw the second line
G1 Z0.4 F3000; Move Z Axis Up
G1 X50 F1500; Wipe to the right
G92 E0 ;Reset Extruder

; Brush any crap off the nozzle
; """""
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
; Filament gcode
M107
;LAYER_CHANGE
;Z:0.35
;HEIGHT:0.35
G1 Z.35 F30000
G1 E-.1 F2400
G92 E0
G1 X97.36 Y95.731 F30000
G1 E.1 F2400
;TYPE:Skirt/Brim
;WIDTH:0.7
G1 F1800
G1 X99.646 Y94.494 E.33635
G1 X102.5 Y94 E.59972
G1 X132.5 Y94 E3.32761
G1 X135.069 Y94.398 E3.56399
G1 X137.398 Y95.554 E3.80042
G1 X139.269 Y97.36 E4.03688
G1 X140.506 Y99.646 E4.27323
G1 X141 Y102.5 E4.5366
G1 X141 Y132.5 E7.26449
G1 X140.602 Y135.069 E7.50087
G1 X139.446 Y137.398 E7.7373
G1 X137.64 Y139.269 E7.97376
G1 X135.354 Y140.506 E8.21011
G1 X132.5 Y141 E8.47348
G1 X102.5 Y141 E11.20137
G1 X99.931 Y140.602 E11.43775
G1 X97.602 Y139.446 E11.67418
G1 X95.731 Y137.64 E11.91064
G1 X94.494 Y135.354 E12.14699
G1 X94 Y132.5 E12.41036
G1 X94 Y102.5 E15.13825
G1 X94.398 Y99.931 E15.37463
G1 X95.554 Y97.602 E15.61106
G1 X97.318 Y95.774 E15.84205
G1 X97.778 Y96.245 F30000
G1 F1800
G1 X97.966 Y96.062 E15.86591
G1 X100.214 Y94.964 E16.0934
G1 X102.5 Y94.625 E16.30354
G1 X132.5 Y94.625 E19.03143
G1 X134.97 Y95.023 E19.25892
G1 X137.191 Y96.175 E19.48642
G1 X138.938 Y97.966 E19.71392
G1 X140.036 Y100.214 E19.94141
G1 X140.375 Y102.5 E20.15155
G1 X140.375 Y132.5 E22.87944
G1 X139.977 Y134.97 E23.10693
G1 X138.825 Y137.191 E23.33443
G1 X137.034 Y138.938 E23.56193
G1 X134.786 Y140.036 E23.78942
G1 X132.5 Y140.375 E23.99956
G1 X102.5 Y140.375 E26.72745
G1 X100.03 Y139.977 E26.95494
G1 X97.809 Y138.825 E27.18244
G1 X96.062 Y137.034 E27.40994
G1 X94.964 Y134.786 E27.63743
G1 X94.625 Y132.5 E27.84757
G1 X94.625 Y102.5 E30.57546
G1 X95.023 Y100.03 E30.80295
G1 X96.175 Y97.809 E31.03045
G1 X97.735 Y96.287 E31.22863
G1 X98.174 Y96.769 F30000
G1 F1800
G1 X98.569 Y96.409 E31.27723
G1 X100.773 Y95.459 E31.49546
G1 X102.5 Y95.25 E31.65364
G1 X132.5 Y95.25 E34.38153
G1 X134.867 Y95.647 E34.59977
G1 X136.974 Y96.796 E34.81799
G1 X138.591 Y98.569 E35.03619
G1 X139.541 Y100.773 E35.25442
G1 X139.75 Y102.5 E35.4126
G1 X139.75 Y132.5 E38.14049
G1 X139.353 Y134.867 E38.35873
G1 X138.204 Y136.974 E38.57695
G1 X136.431 Y138.591 E38.79515
G1 X134.227 Y139.541 E39.01338
G1 X132.5 Y139.75 E39.17156
G1 X102.5 Y139.75 E41.89945
G1 X100.133 Y139.353 E42.11769
G1 X98.026 Y138.204 E42.33591
G1 X96.409 Y136.431 E42.55411
G1 X95.459 Y134.227 E42.77234
G1 X95.25 Y132.5 E42.93052
G1 X95.25 Y102.5 E45.65841
G1 X95.647 Y100.133 E45.87665
G1 X96.796 Y98.026 E46.09487
G1 X98.129 Y96.809 E46.259
G1 X98.544 Y97.301 F30000
G1 F1800
G1 X99.168 Y96.774 E46.33327
G1 X101.32 Y95.981 E46.54181
G1 X102.5 Y95.875 E46.64954
G1 X132.5 Y95.875 E49.37743
G1 X134.759 Y96.272 E49.58599
G1 X136.747 Y97.415 E49.79451
G1 X138.226 Y99.168 E50.00306
G1 X139.019 Y101.32 E50.2116
G1 X139.125 Y102.5 E50.31933
G1 X139.125 Y132.5 E53.04722
G1 X138.728 Y134.759 E53.25578
G1 X137.585 Y136.747 E53.4643
G1 X135.832 Y138.226 E53.67285
G1 X133.68 Y139.019 E53.88139
G1 X132.5 Y139.125 E53.98912
G1 X102.5 Y139.125 E56.71701
G1 X100.241 Y138.728 E56.92557
G1 X98.253 Y137.585 E57.13409
G1 X96.774 Y135.832 E57.34264
G1 X95.981 Y133.68 E57.55118
G1 X95.875 Y132.5 E57.65891
G1 X95.875 Y102.5 E60.3868
G1 X96.272 Y100.241 E60.59536
G1 X97.415 Y98.253 E60.80388
G1 X98.498 Y97.339 E60.93274
G1 E60.83274 F2400
G92 E0
G1 X130.9 Y130.9 F30000
G1 E.1 F2400
;TYPE:Perimeter
;WIDTH:0.7
G1 F1800
G1 X104.1 Y130.9 E2.53691
G1 X104.1 Y104.1 E4.97382
G1 X130.9 Y104.1 E7.41073
G1 X130.9 Y130.84 E9.84219
G1 X131.525 Y131.525 F30000
G1 F1800
G1 X103.475 Y131.525 E12.39276
G1 X103.475 Y103.475 E14.94333
G1 X131.525 Y103.475 E17.4939
G1 X131.525 Y131.465 E20.03902
G1 X132.15 Y132.15 F30000
;TYPE:External perimeter
G1 F1800
G1 X102.85 Y132.15 E22.70326
G1 X102.85 Y102.85 E25.3675
G1 X132.15 Y102.85 E28.03174
G1 X132.15 Y132.09 E30.69052
G1 X131.764 Y132.046 F30000
G1 E30.59052 F2400
G92 E0
G1 X129.428 Y104.287 F30000
G1 E.1 F2400
;TYPE:Solid infill
;WIDTH:0.710021
G1 F1800
G1 X130.432 Y105.29 E.23111
G1 X130.432 Y106.188 E.31407
G1 X128.812 Y104.568 E.52573
G1 X127.914 Y104.568 E.60869
G1 X130.432 Y107.086 E.93768
G1 X130.432 Y107.984 E1.02064
G1 X127.016 Y104.568 E1.46696
G1 X126.118 Y104.568 E1.54992
G1 X130.432 Y108.882 E2.11357
G1 X130.432 Y109.78 E2.19653
G1 X125.22 Y104.568 E2.87751
G1 X124.322 Y104.568 E2.96047
G1 X130.432 Y110.678 E3.75878
G1 X130.432 Y111.576 E3.84174
G1 X123.424 Y104.568 E4.75738
G1 X122.526 Y104.568 E4.84034
G1 X130.432 Y112.474 E5.87331
G1 X130.432 Y113.372 E5.95627
G1 X121.628 Y104.568 E7.10657
G1 X120.731 Y104.568 E7.18944
G1 X130.432 Y114.269 E8.45693
G1 X130.432 Y115.167 E8.53989
G1 X119.833 Y104.568 E9.92471
G1 X118.935 Y104.568 E10.00767
G1 X130.432 Y116.065 E11.50982
G1 X130.432 Y116.963 E11.59278
G1 X118.037 Y104.568 E13.21226
G1 X117.139 Y104.568 E13.29522
G1 X130.432 Y117.861 E15.03203
G1 X130.432 Y118.759 E15.11499
G1 X116.241 Y104.568 E16.96913
G1 X115.343 Y104.568 E17.05209
G1 X130.432 Y119.657 E19.02356
G1 X130.432 Y120.555 E19.10652
G1 X114.445 Y104.568 E21.19532
G1 X113.547 Y104.568 E21.27828
G1 X130.432 Y121.453 E23.48441
G1 X130.432 Y122.351 E23.56737
G1 X112.649 Y104.568 E25.89082
G1 X111.752 Y104.568 E25.97369
G1 X130.432 Y123.248 E28.41434
G1 X130.432 Y124.146 E28.4973
G1 X110.854 Y104.568 E31.05528
G1 X109.956 Y104.568 E31.13824
G1 X130.432 Y125.044 E33.81355
G1 X130.432 Y125.942 E33.89651
G1 X109.058 Y104.568 E36.68915
G1 X108.16 Y104.568 E36.77211
G1 X130.432 Y126.84 E39.68208
G1 X130.432 Y127.738 E39.76504
G1 X107.262 Y104.568 E42.79234
G1 X106.364 Y104.568 E42.8753
G1 X130.432 Y128.636 E46.01993
G1 X130.432 Y129.534 E46.10289
G1 X105.466 Y104.568 E49.36485
G1 X104.568 Y104.569 E49.44781
G1 X130.431 Y130.432 E52.82696
G1 X129.534 Y130.432 E52.90983
G1 X104.568 Y105.466 E56.17179
G1 X104.568 Y106.364 E56.25475
G1 X128.636 Y130.432 E59.39938
G1 X127.738 Y130.432 E59.48234
G1 X104.568 Y107.262 E62.50964
G1 X104.568 Y108.16 E62.5926
G1 X126.84 Y130.432 E65.50257
G1 X125.942 Y130.432 E65.58553
G1 X104.568 Y109.058 E68.37817
G1 X104.568 Y109.956 E68.46113
G1 X125.044 Y130.432 E71.13644
G1 X124.146 Y130.432 E71.2194
G1 X104.568 Y110.854 E73.77738
G1 X104.568 Y111.752 E73.86034
G1 X123.248 Y130.432 E76.30099
G1 X122.35 Y130.432 E76.38395
G1 X104.568 Y112.65 E78.70727
G1 X104.568 Y113.547 E78.79014
G1 X121.453 Y130.432 E80.99627
G1 X120.555 Y130.432 E81.07923
G1 X104.568 Y114.445 E83.16803
G1 X104.568 Y115.343 E83.25099
G1 X119.657 Y130.432 E85.22246
G1 X118.759 Y130.432 E85.30542
G1 X104.568 Y116.241 E87.15956
G1 X104.568 Y117.139 E87.24252
G1 X117.861 Y130.432 E88.97933
G1 X116.963 Y130.432 E89.06229
G1 X104.568 Y118.037 E90.68177
G1 X104.568 Y118.935 E90.76473
G1 X116.065 Y130.432 E92.26688
G1 X115.167 Y130.432 E92.34984
G1 X104.568 Y119.833 E93.73466
G1 X104.568 Y120.731 E93.81762
G1 X114.269 Y130.432 E95.08511
G1 X113.371 Y130.432 E95.16807
G1 X104.568 Y121.629 E96.31823
G1 X104.568 Y122.526 E96.4011
G1 X112.474 Y130.432 E97.43407
G1 X111.576 Y130.432 E97.51703
G1 X104.568 Y123.424 E98.43267
G1 X104.568 Y124.322 E98.51563
G1 X110.678 Y130.432 E99.31394
G1 X109.78 Y130.432 E99.3969
G1 X104.568 Y125.22 E100.07788
G1 X104.568 Y126.118 E100.16084
G1 X108.882 Y130.432 E100.72449
G1 X107.984 Y130.432 E100.80745
G1 X104.568 Y127.016 E101.25377
G1 X104.568 Y127.914 E101.33673
G1 X107.086 Y130.432 E101.66572
G1 X106.188 Y130.432 E101.74868
G1 X104.568 Y128.812 E101.96034
G1 X104.568 Y129.71 E102.0433
G1 X105.572 Y130.713 E102.17441
G1 E102.07441 F2400
G92 E0
M107
;TYPE:Custom
; Filament-specific end gcode
M104 S0 ; turn off temperature
M140 S0 ; turn off both beds
G28 X0  ; home X axis
M84     ; disable motors
; filament used [mm] = 223.50
; filament used [cm3] = 0.54
; filament used [g] = 0.67
; filament cost = 0.01
; total filament used [g] = 0.67
; total filament cost = 0.01
; estimated printing time (normal mode) = 1m 32s
; estimated first layer printing time (normal mode) = 1m 32s

; prusaslicer_config = begin
; autoemit_temperature_commands = 0
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = /home/jacques/.config/PrusaSlicer/printer/Grid Texture 220x220.png
; bed_shape = 0x0,235x0,235x235,0x235
; bed_temperature = 60
; before_layer_gcode = 
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 150
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; color_change_gcode = M600
; compatible_printers_condition_cummulative = ;"printer_notes!~/.*PRINTER_VENDOR_TRILAB.*/ and printer_notes!~/.*PRINTER_MODEL_MK4IS.*/ and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and num_extruders>1)"
; complete_objects = 0
; cooling = 0
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = 
; default_print_profile = 
; deretract_speed = 0
; disable_fan_first_layers = 3
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 1
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = M104 S0 ; turn off temperature\nM140 S0 ; turn off both beds\nG28 X0  ; home X axis\nM84     ; disable motors\n
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #000000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 16.9
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 14
; filament_loading_speed_start = 19
; filament_max_volumetric_speed = 25
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_length = 0.1
; filament_retract_speed = 40
; filament_settings_id = "Elegoo Black PLA"
; filament_soluble = 0
; filament_spool_weight = 1000
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 20
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; fill_angle = 45
; fill_density = 20%
; fill_pattern = adaptivecubic
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 65
; first_layer_extrusion_width = 200%
; first_layer_height = 0.35
; first_layer_speed = 30
; first_layer_speed_over_raft = 30
; first_layer_temperature = 205
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 50
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 0
; gcode_resolution = 0.0125
; gcode_substitutions = ;;;
; high_current_on_filament_swap = 0
; host_type = prusalink
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_first = 0
; infill_overlap = 25%
; infill_speed = 100
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = 
; layer_height = 0.3
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 10000,5000
; machine_max_acceleration_extruding = 1500,1250
; machine_max_acceleration_retracting = 1500,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 9000,1000
; machine_max_acceleration_y = 9000,1000
; machine_max_acceleration_z = 500,200
; machine_max_feedrate_e = 199,199
; machine_max_feedrate_x = 500,200
; machine_max_feedrate_y = 500,200
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.2,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0
; max_print_height = 265
; max_print_speed = 500
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 25
; min_bead_width = 85%
; min_fan_speed = 35
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 10
; min_skirt_length = 0
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_generator = arachne
; perimeter_speed = 75
; perimeters = 3
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = Elegoo Neptune4 Pro Prototyping
; printer_model = 
; printer_notes = This is my (Jacques Blain) custom Elegoo Neptune 4 Pro setup
; printer_settings_id = Elegoo Neptune 4 Pro
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 4
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 5
; small_perimeter_speed = 25%
; solid_infill_acceleration = 0
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 70
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = ; M190 R30 ; Because of probe temperature drift,\n; M109 R30 ; Let the beds and hotend cool down before homing the axis\n\nG28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\nM190 S[first_layer_bed_temperature] ; set bed temperature and wait for it to be reached\nM109 S[first_layer_temperature] ; set hot end temp and wait for it\n\n; Do a purge line to prime the extruder\nG92 E0 ;Reset Extruder\nG1 Z2.0 F3000 ;Move Z Axis up\nG1 X20 Y5.1 Z0.28 F5000.0 ;Move to start position\nG1 X200.0 Y5.1 Z0.28 F1500.0 E15 ;Draw the first line\nG1 X200.0 Y5.4 Z0.28 F5000.0 ;Move to side a little\nG1 X20 Y5.4 Z0.28 F1500.0 E30 ;Draw the second line\nG1 Z0.4 F3000; Move Z Axis Up\nG1 X50 F1500; Wipe to the right\nG92 E0 ;Reset Extruder\n\n; Brush any crap off the nozzle\n; """""
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 1
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 1
; support_material_interface_extruder = 1
; support_material_interface_layers = 1
; support_material_interface_pattern = concentric
; support_material_interface_spacing = 0.6
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 10
; support_material_speed = 75
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 0
; support_material_xy_spacing = 50%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 15%
; temperature = 195
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 1
; threads = 4
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 60
; top_solid_layers = 3
; top_solid_min_thickness = 0
; travel_acceleration = 0
; travel_speed = 500
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
